// <auto-generated />
using System;
using ApplicantTracking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicantTracking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114060326_FirstMigrationApplicant")]
    partial class FirstMigrationApplicant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicantTracking.Domain.DTO.Candidate", b =>
                {
                    b.Property<int>("IdCandidate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCandidate");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidate"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCandidate");

                    b.ToTable("candidates", "dbo");
                });

            modelBuilder.Entity("ApplicantTracking.Domain.DTO.Timeline", b =>
                {
                    b.Property<int>("IdTimeline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTimeline");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTimeline"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAggregateRoot")
                        .HasColumnType("int");

                    b.Property<byte>("IdTimelineType")
                        .HasColumnType("tinyint");

                    b.Property<string>("NewData")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("varchar(max)");

                    b.HasKey("IdTimeline");

                    b.ToTable("timelines", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
